version: '3.8'

services:
  db:
    image: postgres:15
    container_name: taller_liquibase_db
    restart: always
    environment:
      POSTGRES_DB: mgbd_liquibase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mgbd_liquibase"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.25
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/liquibase/changelog
    working_dir: /liquibase/changelog
    entrypoint: ["liquibase"]
    command: ["--help"]

volumes:
  postgres_data:
